### ISSUE TITLE
Decide whether to use arrow or normal functions

### ISSUE THREAD

**Issue by maanlamp** [jesperingels/web-app-from-scratch-18-19#2]
https://github.com/jesperingels/web-app-from-scratch-18-19/blob/0c6d2dbdb795f8fccd71fa53e58bac987024de26/week1/public/js/app.js#L48

Here you're using a `function` expression instead of an arrow function. You're using arrow functions everywhere else. Any reason why? You're not using `this`...

**Comment by jesperingels** [comment]
Started using modules today
