### ISSUE TITLE
Use forEach?

### ISSUE THREAD

**Issue by maanlamp** [jesperingels/web-app-from-scratch-18-19#3]
https://github.com/jesperingels/web-app-from-scratch-18-19/blob/0c6d2dbdb795f8fccd71fa53e58bac987024de26/week1/public/js/app.js#L67-L76

`Array.map` returns a new array. You're not using the return value of this `.map` operation, consider using `Array.forEach()` instead.

**Comment by jesperingels** [comment]
Heb nu de forEach(); toegepast, ipv .map. thx!
